server:
  port: 9000
  
spring:
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher
      
  datasource:
    url: jdbc:mysql://localhost:3306/olxLogin
    username: root
    password: root
  jpa:
    properties:
      hibernate:
           format_sql: true
    hibernate:
      ddl-auto: update
    show-sql: true
    
management:
  endpoints:
    web:
      exposure:
        include:
        - "*"
        exclude:
        
      base-path: "/my-actuator"